### ISSUE TITLE
仕様書作成

### ISSUE THREAD

**Issue by panmatsu** [nalgo-intern/teamA#13]

**Comment by ShrMatsuoka** [comment]
ざっくり作成しました。
文書等不備あると思いますので適宜修正していきます。

f0d03f5

**Comment by ta-iwa** [comment]
プルリクエスト投げてもらえれば、レビューしますよ。

**Comment by ta-iwa** [comment]
mention PL #63

**Comment by ShrMatsuoka** [comment]
暫定版 #63
 
*追記検討事項
解錠されたことをユーザはどこで判断できるのか
アプリケーションの使用方法
など
