### ISSUE TITLE
シルエットの面積計算

### ISSUE THREAD

**Issue by ba-hira** [nalgo-intern/teamA#4]

**Comment by ShrMatsuoka** [comment]
ブランチの方ですがあげてあります。
白面積の計算です。
[https://github.com/nalgo-intern/teamA/blob/feature/member-matsuoka/borw.py](url)

**Comment by ta-iwa** [comment]
URLが404になってしまっていますね。

該当するコミット番号を貼り付けるとそのコミットに対してリンクができますよ。

d516d8638433f55d

**Comment by ShrMatsuoka** [comment]
申し訳ありません、確認不足でした。
変更いたしました。

**Comment by ShrMatsuoka** [comment]
追加、同じくブランチです。
白面積の計算に加え、二つの画像の比較を可能にしました。
現在は暫定で差の算出になっています。

cb81787
