### ISSUE TITLE
レポジトリ内をきれいにする

### ISSUE THREAD

**Issue by panmatsu** [nalgo-intern/teamA#49]
具体的にはフォルダわけ

**Comment by panmatsu** [comment]
フォルダの作り方
http://d.hatena.ne.jp/yohei-a/20090715/1247638668
フォルダ名のつけ方
http://qiita.com/Mogu_ff/items/a93ca38b5bdf3eaca53b

**Comment by ta-iwa** [comment]
マージが済んだ不要なブランチも削除してほしいです。

Closeされたプルリクエストのページに、ブランチを削除するボタンがあるのでそれで消してください。

**Comment by panmatsu** [comment]
いくつか消しました

**Comment by panmatsu** [comment]
レポジトリ内に
doc
src
script
フォルダを作成
