### ISSUE TITLE
DBのテーブル項目の調整

### ISSUE THREAD

**Issue by ShrMatsuoka** [nalgo-intern/teamA#54]
現状
id / name / markrt / markrb / marklt / marklb / silhouette
name, silhouetteは文字列、他は数値が入る

希望等あればコメントしておいてください

追記めも
checkの後半でそれぞれidnum, name, rt, rb, lt, lb, poseという変数に保存

**Comment by ShrMatsuoka** [comment]
cebc386
ｃｓｖファイルは現在不適当

**Comment by panmatsu** [comment]
現状マーカー左右のxyが数値で入れば問題ないです

**Comment by ShrMatsuoka** [comment]
@panmatsu 
了解です
