### ISSUE TITLE
DBに登録する鍵の作成

### ISSUE THREAD

**Issue by ShrMatsuoka** [nalgo-intern/teamA#68]
マーカー座標コメント等で共有してください

**Comment by ShrMatsuoka** [comment]
一応シルエット画像
e3c14bb 

DBから引き出すために一括でimgフォルダに入れてます。
※dbkey.dbは不完全

**Comment by panmatsu** [comment]
エラー落ち対応してサンプル動画から赤円認識してみたところ思ってた以上にマーカーを認識できず、マーカー鍵を作れてないです

**Comment by panmatsu** [comment]
[https://github.com/nalgo-intern/teamA/tree/test/marker](url)
で確認できます

**Comment by panmatsu** [comment]
[http://whitecat-student.hatenablog.com/entry/2016/11/09/225631](url)
鍵マーカー座標作ります

**Comment by ShrMatsuoka** [comment]
@panmatsu 
よろしくお願いします！
[マウスクリック](http://whitecat-student.hatenablog.com/entry/2016/11/09/225631)

**Comment by panmatsu** [comment]
- marker_key01
　左鍵、左上x:240、y:110、右下x:285、y:150
　右鍵、左上x:420、y:260、右下x:473、y:300

- marker_key02
　左鍵、左上x:250、y:100、右下x:295、y:135
　右鍵、左上x:360、y:100、右下x:400、y:150

- marker_key03
　左鍵、左上x:240、y:170、右下x:280、y:210
　右鍵、左上x:340、y:270、右下x:390、y:315

**Comment by panmatsu** [comment]
追記：
右鍵、左鍵は、カメラの画像から右か左です
被験者の持ち手ではないです

**Comment by ShrMatsuoka** [comment]
左右の鍵ってそれぞれ取り出せるほうがいいですかね？
たとえばtanaka-leftの値とtanaka-rightの値みたいな

**Comment by panmatsu** [comment]
一緒に処理するので一括でいいでよ

**Comment by ShrMatsuoka** [comment]
DBmemo
create table keyset (
    id integer unique not null,
    name text not null,
    left_ltx integer not null,
    left_lty integer not null,
    left_rbx integer not null,
    left_rby integer not null,
right_***であと4つ
    pose text not null
