### ISSUE TITLE
アプリケーションの使い方をREADMEに記載する

### ISSUE THREAD

**Issue by ta-iwa** [nalgo-intern/teamA#97]
作成したアプリケーションの使い方をREADMEに追加してください。
Usageという章を作ってそこに記載してください。

修正内容はプルリクエストを作って、レビューします。

書き方は他のGithubのリポジトリを参考にしてください。

https://github.com/ReactiveX/RxJava
https://github.com/wg/wrk

**Comment by ta-iwa** [comment]
https://github.com/nalgo-intern/teamB/issues/51
https://github.com/nalgo-intern/teamC/issues/56

**Comment by panmatsu** [comment]
退勤前に急いでコミットして家でプルリク送ろうとしたらコミットされてませんでした。

**Comment by panmatsu** [comment]
#112
プルリク送りました。

**Comment by ShrMatsuoka** [comment]
お疲れ様です…ありがとうございます！
